=encoding utf8

=head1 NAME

brailleimg - convert an image to text using Braille range glyphs

=head1 SYNOPSIS

B<brailleimg> [B<-r>] [B<-t> I<128>] I<image.png>

=head1 DESCRIPTION

B<brailleimg> is a tool to convert images to a black-and-white textual
representation abusing glyphs meant for representation of Braille
(U+2800..U+28FF).  Obviously, this requires Unicode support, but nowadays
all mail clients, web browsers, graphical terminals, forums (other than
Slashdot) do support Unicode.  The resolution is 2E<times>4 per
character, so an 80E<times>25 terminal can display images up to
160E<times>100 without scrolling.  A kosher mail .signature is limited to 16
pixels height, and so on.

Images tend to use resolutions many times higher than this, thus you'll
usually need to rescale them beforehand.  For most images rescaling in a way
that's reasonable with 1-bit color is tricky, thus you probably want to do
this interactively using a tool like B<GIMP>.  For scripted work, there's
B<ImageMagick>.

Most of popular image formats are supported, using B<libgd>.

=head1 OPTIONS

=over

=item B<-r>, B<--reverse>

Selects black-on-white mode.  Normally, bright colours are rendered as "ink"
(which is typically whiteish on terminals and black on web pages), dark as
"paper"; this option reverses this.  You'll usually want this option for
images that go web forums; any right-thinking UNIX hacker uses
white or lightgray or green or amber on black so the default is tailored for
terminals.

=item B<-t>, B<--threshold> I<number>

Sets the brightness cutoff (default 128), in a scale of 0..255.  Currently
the comparison is done by averaging RGB values, in a subsequent version this
may change to a nicer color space, like what B<GIMP> does.

=back

=head1 CAVEATS

Versions of FreeFont older than end of 2016 make any Braille glyphs (both
for legitimate uses and for B<brailleimg>) totally unreadable at pixel sizes
commonly found in computer displays — ie, anything but HiDPI and/or very
large text sizes.  Alas, this font is commonly configured as primary
fallback in default setups shipped by distributions.

=head1 AUTHOR

Adam Borowski <kilobyte@angband.pl>
